language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

env:
    - SYMFONY_VERSION="2.1.*"
    - SYMFONY_VERSION="2.2.*"

before_script:
    - composer install --dev

script: bin/phpunit

notifications:
    email: benjamin.lazarecki@gmail.com
